name: ratozap_chat
description: Aplicativo de chat em tempo real com Flutter e Supabase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  uuid: ^4.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_app.png"
  adaptive_icon_background: "#ffffff"   # pode ser cor
  adaptive_icon_foreground: "assets/logos/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/